### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Yang-Li-Chang** [Chiangsonw/CaLa#2]
Dear author, I noticed a bug in the loss calculation section of the file blip_fine_tune.py, from line 867 to 874. No matter the condition, the loss will be covered by contrastive_loss, which may cause the reasoning_loss to be ignored when hca_weight > 0. I would appreciate your response,Thank you :)
![Screenshot 2024-09-14 211335](https://github.com/user-attachments/assets/c3ab9a3c-60e9-4ebd-bef1-ae1536aaa9c7)

**Comment by Chiangsonw** [comment]
Thanks!  I made a mistake while tidying up the code, which caused the bug. I have already fixed it.
![image](https://github.com/user-attachments/assets/8b137f46-ba0c-4218-8d78-43eabaae5e93)
