### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Yang-Li-Chang** [Chiangsonw/CaLa#3]
Dear author, I have noticed a bug in line 342 and 811 of the file blipufine_tune. py. The function encode_text(), which encodes text using the CLIP model, only returns one value, but your code expects two, which results in an error during training.
![Screenshot 2024-09-19 132928](https://github.com/user-attachments/assets/cb0b1f31-96d8-4f32-b5f9-df3b1a00dfeb)
Another issue is that you mentioned in the readme that you want to replace some codes in the clip packages. Is there a spelling error in the newly replaced code? The self. attnpool was written as self. attepool.I would appreciate your response,Thank you :)
![Screenshot 2024-09-19 133702](https://github.com/user-attachments/assets/2d38f9a4-426e-49fe-a1a8-3011e7c719a9)

**Comment by Chiangsonw** [comment]
Thank you for the bug report, you see the reason I modified the CLIP package is to get the global features (shape like [Batchsize, NumOfSequence,TransformerWidth]. I made the similar changes for clip.encode_image() and clip.encode_text(), which can be found in the updated readme file.

**Comment by Chiangsonw** [comment]
Here is the changes for text_encode()

```

#Replace CLIP/clip/models.py line 343-356 with the following codes. Before get the cls token, get the feature sequence of text as text global features.
 346#   x = x + self.positional_embedding.type(self.dtype)
 347#   x = x.permute(1, 0, 2)  # NLD -> LND
 348#   x = self.transformer(x)
 349#   x = x.permute(1, 0, 2)  # LND -> NLD
 350#   x = self.ln_final(x).type(self.dtype)
 351#
 352#   y = x
 353#   # x.shape = [batch_size, n_ctx, transformer.width]
 354#   # take features from the eot embedding (eot_token is the highest number in each sequence)
 355#   x = x[torch.arange(x.shape[0]), text.argmax(dim=-1)] @ self.text_projection

 356#   return x,y

```
Welcome to ask is anything unclear.

**Comment by Yang-Li-Chang** [comment]
Thanks for your response. My question has been successfully resolved.

**Comment by Chiangsonw** [comment]
You are welcome!
