### ISSUE TITLE
The learning rate for FashionIQ dataset.

### ISSUE THREAD

**Issue by li-shuxian** [Chiangsonw/CaLa#4]
Dear author, I'm interested in your work, CaLa, and am trying to reproduce it. Is the learning rate for FashionIQ 1e-5 or 5e-6? Although the paper suggests a learning rate of 1e-5 for FashionIQ, the default code uses 5e-6.

Thanks.

**Comment by Chiangsonw** [comment]
Please follow the paper and set the learning rate at 1e-5
